// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

package echo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{0}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RespType struct {
	Resp                 *any.Any `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespType) Reset()         { *m = RespType{} }
func (m *RespType) String() string { return proto.CompactTextString(m) }
func (*RespType) ProtoMessage()    {}
func (*RespType) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{1}
}

func (m *RespType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespType.Unmarshal(m, b)
}
func (m *RespType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespType.Marshal(b, m, deterministic)
}
func (m *RespType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespType.Merge(m, src)
}
func (m *RespType) XXX_Size() int {
	return xxx_messageInfo_RespType.Size(m)
}
func (m *RespType) XXX_DiscardUnknown() {
	xxx_messageInfo_RespType.DiscardUnknown(m)
}

var xxx_messageInfo_RespType proto.InternalMessageInfo

func (m *RespType) GetResp() *any.Any {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterType((*String)(nil), "echo.String")
	proto.RegisterType((*RespType)(nil), "echo.RespType")
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor_08134aea513e0001) }

var fileDescriptor_08134aea513e0001 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x24, 0xd3, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0xc1, 0x62, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95, 0x10, 0x05, 0x4a, 0x72,
	0x5c, 0x6c, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x92, 0x09, 0x17, 0x47, 0x50, 0x6a,
	0x71, 0x41, 0x48, 0x65, 0x41, 0xaa, 0x90, 0x06, 0x17, 0x4b, 0x51, 0x6a, 0x71, 0x01, 0x58, 0x01,
	0xb7, 0x91, 0x88, 0x1e, 0xc4, 0x54, 0x3d, 0x98, 0xa9, 0x7a, 0x8e, 0x79, 0x95, 0x41, 0x60, 0x15,
	0x46, 0x9c, 0x5c, 0xec, 0xae, 0xc9, 0x19, 0xf9, 0xc1, 0xa9, 0x65, 0x49, 0x6c, 0x60, 0x69, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x70, 0xe6, 0xd9, 0x96, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoSevClient is the client API for EchoSev service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoSevClient interface {
}

type echoSevClient struct {
	cc *grpc.ClientConn
}

func NewEchoSevClient(cc *grpc.ClientConn) EchoSevClient {
	return &echoSevClient{cc}
}

// EchoSevServer is the server API for EchoSev service.
type EchoSevServer interface {
}

// UnimplementedEchoSevServer can be embedded to have forward compatible implementations.
type UnimplementedEchoSevServer struct {
}

func RegisterEchoSevServer(s *grpc.Server, srv EchoSevServer) {
	s.RegisterService(&_EchoSev_serviceDesc, srv)
}

var _EchoSev_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echo.EchoSev",
	HandlerType: (*EchoSevServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "echo.proto",
}
