package main

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *Meta) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Sid"
	o = append(o, 0x82, 0xa3, 0x53, 0x69, 0x64)
	o = msgp.AppendString(o, z.Sid)
	// string "Bytes"
	o = append(o, 0xa5, 0x42, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Bytes)))
	for za0001 := range z.Bytes {
		o = msgp.AppendBytes(o, z.Bytes[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Meta) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Sid":
			z.Sid, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sid")
				return
			}
		case "Bytes":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
			if cap(z.Bytes) >= int(zb0002) {
				z.Bytes = (z.Bytes)[:zb0002]
			} else {
				z.Bytes = make([][]byte, zb0002)
			}
			for za0001 := range z.Bytes {
				z.Bytes[za0001], bts, err = msgp.ReadBytesBytes(bts, z.Bytes[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Bytes", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Meta) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.Sid) + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Bytes {
		s += msgp.BytesPrefixSize + len(z.Bytes[za0001])
	}
	return
}
